kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: job-creator
subjects:
  - kind: ServiceAccount
    name: default
    namespace: raccoon
roleRef:
  kind: Role
  name: job-creator
  apiGroup: rbac.authorization.k8s.io
